__article_type__ = {
    "家庭": ["妈妈", "丈夫", "母爱", "物质", "女儿", "女童", "母亲", "坚强", "家暴"],
    "冒险": ["游戏", "故事", "勇敢者", "刺激", "惊险", "故事", "探索"],
    "总结": ["自己", "我", "进步", "越来越", "自我", "生活", "计划"],
    "影视": ["观众", "金马", "演员", "角色", "电影", "电视剧", "电视", "广电总局", "动画", "影片"],
    "影评": ["这部", "欢迎", "感受", "觉得", "对", "观影", "上映", "推荐", ],
    "历史": ["幸存", "幸存者", "经历", "纪录", "苦难"],
    "情感": ["恋爱", "考量", "交流", "快乐", "爱情", "焦虑", "痛苦", "美好"]
}

__chinese_meaningless_word__ = ["的", "了", "他", "她", "它", "是", "中", "是", "在", "到", "也", "《"]

readers = {'Favre': ['亚洲的去魔化\n'
           '\n'
           'Die Entzauberung Asiens: Europa und die asiatischen Reiche im '
           '18. Jahrhundert',
           '守门员面对罚点球时的焦虑\n\nDie Angst des Tormanns beim Elfmeter',
           'How to Increase Your Word Power',
           '俄罗斯列宾美术学院珍藏素描精品选',
           'Major Problems in the History of the Vietnam War',
           'Warriors',
           '甲陽軍鑑\n\n甲陽軍鑑',
           '戰爭論',
           '中国哲学简史\n\nA Short History of Chinese Philosophy',
           '道德经'],
 'Harry': ['面纱\n\nThe Painted Veil',
           '思虑20世纪\n\nThinking the Twentieth Century',
           '哈佛中国史（全六卷）\n\nHistory of Imperial China',
           '生命的跃升\n\nLife Ascending: The Ten Great Inventions of Evolution',
           '大历史\n\nBig History: Between Nothing and Everything',
           '极品家丁全集',
           '匆匆那年',
           '花开半夏',
           '我与地坛',
           '麦田里的守望者\n\nThe Catcher in the Rye'],
 'Kardinal Waltz': ['The Price of Salt',
                    'Emerging from the Euro Debt Crisis',
                    'Resolving the European Debt Crisis',
                    'Introduction to Social Research',
                    '地理学\n'
                    '\n'
                    'Die Geographie: Ihre Geschchte, Ihr Wesen Und Ihre '
                    'Methoden',
                    '永恒的边缘\n\nEdge of Eternity',
                    '圣殿春秋（上）\n\nThe Pillars of the Earth',
                    'NGOs im Prozess der Globalisierung',
                    'Dead Aid',
                    'Lonely Planet Norway'],
 'LORENZO': ['Call Me by Your Name',
             'Cryptonomicon\n\n密宗战史',
             'Maurice',
             '穆斯林的葬礼',
             '流浪者的乡愁',
             '丰饶之海（上下）',
             '尤利西斯',
             '卡拉马佐夫兄弟\n\nБра́тья Карама́зовы'],
 'Lev Kovacs': ['Justice League: The Art of the Film',
                '狗狗学问大',
                'Suicide Squad',
                'The Hobbit: The Battle of the Five Armies, Chronicles: The '
                'Art of War',
                '需要时，就给我电话\n\nCall if you need me',
                '坏狐狸\n\nLe grand mechant renard',
                '如何在派对上搭讪女孩\n\nHow to Talk to Girls at Parties',
                '周三漫画\n\nWednesday Comics',
                '睡魔3：梦境国度\n\nThe Sandman, Vol. 3: Dream Country',
                '恶意之山'],
 'Remi': ['Nederlands op niveau Neu. Lehrbuch + Internet-Zugangscode',
          'Derde ronde',
          'Linear Statistical Inference and its Applications',
          'Multivariate Analysis (Probability and Mathematical Statistics)',
          'Time Series Analysis',
          'George F. Kennan',
          'Probability',
          'Functional Analysis (Springer Classics in Mathematics)',
          'Theory of Functions of a Real Variable',
          'Linear Algebra and Its Applications'],
 'Somnambule': ['当我谈跑步时我谈些什么\n\n走ることについて語るときに僕の語ること',
                '史蒂夫·乔布斯传\n\nSteve Jobs: A Biography',
                'The Art of Travel',
                'The Art and Science of Java',
                '德语翻译入门',
                '心理学与生活\n\nPsychology and life',
                '霍乱时期的爱情',
                '百年孤独\n\nCien años de soledad',
                '昨日的世界\n\nDie Welt von Gestern: Erinnerungen eines Europäers',
                '柳如是别传（全三册）'],
 'birds': ['未知大学',
           '长日留痕\n\nThe Remains of the Day',
           '印象与风景',
           '昨天的云',
           '洞察：精确观察和有效沟通的艺术',
           '娜塔莎之舞',
           '创造日本',
           '新千年幻想',
           '第一个坏人\n\nThe First Bad Man'],
 'sb莉莉': ['系统思考',
          '自戀時代\n\nNarcissism Epidemic :Living in the Age of Entitlement',
          '危险，切勿把头伸进来！',
          '守望的距离',
          '各自的朝圣路'],
 'yum': ['Sweet Tooth',
         'Mencken Chrestomathy',
         'The Idle Thoughts of an Idle Fellow, a Book for an Idle Holiday',
         'The Buddha of Suburbia\n\n郊区佛陀',
         'Three Men in a Boat',
         'More Die of Heartbreak',
         'The Bad Beginning',
         '欢迎来到猴子馆\n\nWelcome to the Monkey House',
         'Consider The Lobster',
         'Before We Were Yours: A Novel'],
 '† Rehoboth': ['里尔克的绝唱',
                '纪录片编导与制作',
                '创意能源库',
                '做最创意的节目',
                '胡若望的困惑之旅',
                '灯光师圣经（插图第4版）\n\nSet Lighting Technician’s Handbook,4e',
                '冰点\n\n氷点',
                '鲁愚力钢笔画集',
                '加尔文论崇拜\n\nIN THE SPLENDOR OF HOLINESS',
                '历史遗留的证据\n\nHeritage of Evidence in the British Museum'],
 '。o': ['卡夫卡书信日记选',
        '关于电影',
        '长眠不醒',
        '石川啄木诗歌集',
        "安吉拉·卡特的精怪故事集\n\nAngela Carter's Book of Fairy Tales",
        '沙与沫',
        '凯尔特的薄暮\n\nThe Celtic Twilight'],
 '一个影迷': ['艳骨'],
 '一米阳光': ['七号房的礼物\n\n7번방의 선물',
          '嫌疑人X的献身\n\n容疑者Xの献身',
          '三体Ⅲ',
          '三体Ⅱ',
          '三体',
          '巴黎圣母院\n\nNotre-Dame de Paris',
          '童年',
          '安娜·卡列尼娜',
          '战争与和平',
          '我的大学'],
 '与狼共舞': ['三体',
          '世界的凛冬\n\nWinter of the World',
          '巨人的陨落\n\nFall of Giants',
          '天堂沉默半小時',
          '半小时漫画中国史（修订版）',
          '少年维特的烦恼\n\nDie Leiden des jungen Werthers',
          '夜话港乐2',
          '教父\n\nThe Godfather',
          '教父家族',
          '冷血\n\nIn Cold Blood'],
 '丑阿荣': ['宽忍的灰色黎明',
         '思想史：从火到弗洛伊德\n\nIdeas: A History from Fire to Freud',
         '我的奋斗1\n\nMin Kamp 1',
         '卡繆札記 I\n\nCarnets I, mai 1935-février 1942',
         '书海泛舟记',
         '康德三大批判精粹'],
 '之晨': ['孩子们的诗', '摇摇晃晃的人间', '再袭面包店\n\nパン屋再襲撃', '新参者\n\n新参者', '活着本来单纯'],
 '乐先生': ['最新国际版式设计',
         'PHOTOSHOP CS/CS2 WOW!BOOK',
         '设计中的设计',
         '设计，不安于室',
         '大便书\n\nUNCOCORO for NATURAL UNCO LIFE',
         '两百年的孩子',
         'The Polaroid Book',
         'Oh! My God! I Miss You',
         'Logo',
         'Drawing File'],
 '于念慈': ['贾想II',
         '花樣的年華·澤東廿五',
         '大卫·鲍伊',
         '神行陌路',
         '酒友 饭友\n\n酒の友 めしの友',
         '伦勃朗\n\nREMBRANDT',
         '笑场',
         '寻找沃霍尔\n\nWhere’s Warhol',
         '如何在派对上搭讪女孩\n\nHow to Talk to Girls at Parties',
         '無限的網\n\n無限の網: 草間彌生自伝'],
 '亦栈': ['And the Mountains Echoed',
        'Tinker, Tailor, Soldier, Spy',
        'Fall of Giants',
        'A Beautiful Mind',
        '风声鹤唳',
        '神的九十亿个名字\n\nOf time and stars',
        '最后十二天的生命之旅',
        '安拉.别为我哭泣\n\n丝芭·沙克布',
        '脆弱的时光',
        '镜子外的福尔摩斯\n\nBending the Willow: Jeremy Brett as Sherlock Holmes'],
 '公益霎哈嘉瑜伽': ['论语遇上圣经',
             '蔡志忠漫画·中国传统文化经典·漫画中国思想系列：大学·中庸·论语·孟子说（中英对照版）',
             '蔡志忠漫画中国传统文化经典:老子说(中英文对照版)\n\n蔡志忠',
             '迷娘曲',
             '辜鸿铭讲论语',
             '任继愈论儒佛道',
             '儒道释与内在超越问题',
             '中国传统文化的儒道释',
             '老子注',
             '中庸'],
 '冠素': ['专注力',
        '巴赫花精与自我疗愈\n\nHeal Thyself / The Twelve Healers and Other Remedies',
        '中国美学十五讲',
        '南画十六观',
        '只若初见，似已相知',
        '最初和最终的自由',
        '飞鸟集',
        '今天也要用心過生活\n\n今日もていねいに｡',
        '风雨哈佛路\n'
        '\n'
        'Breaking Night: A Memoir of Forgiveness, Survival, and My Journey '
        'from Homeless to Harvard',
        '寻路中国\n'
        '\n'
        'Country Driving: A Journey Through China from Farm to Factory'],
 '冷雨醉清秋': ['不成问题的问题', '小王子\n\nLe Petit Prince'],
 '冻泥大口': ['色情史',
          '忧郁的热带',
          '如何在派对上搭讪女孩\n\nHow to Talk to Girls at Parties',
          '思想史：从火到弗洛伊德\n\nIdeas: A History from Fire to Freud',
          '论自由\n\nOn Liberty',
          '无限与视角\n\nInfinity and Perspective',
          '冥河的摆渡者'],
 '凌玥轩☪': ['岁月如风小少年',
          '月童度河',
          '我们从未陌生过',
          '白说',
          '我坚信\n\nWhat I Know For Sure',
          '喜剧作家',
          '夜色人生\n\nLive by Night',
          '自在独行',
          '再见，少年',
          '解忧杂货店\n\nナミヤ雑貨店の奇蹟'],
 '卧槽钰帝': ['伊甸園01\n\nEDEN',
          '不思議庭園の魔物',
          '人でなしの恋 (いずみコミックス)',
          '思春期のアイアンメイデン 1',
          '扭曲的同居生活 1\n\nいびつ',
          '新暗行御史(共17册)',
          '魔女(01)',
          '異變者1',
          '邻座的怪同学 1\n\nとなりの怪物くん',
          'ZERO\n\nゼロ'],
 '去年槲寄生': ['西方电影史论',
           'Frances Ha',
           "Terry O'Neill",
           '当代电影分析',
           '琴声如诉\n\nModerato Cantabile'],
 '哪吒男': ['图像学\n\nIconology: Image Text Ideology',
         '图像学',
         '图像学研究\n'
         '\n'
         'Studies in Iconology:Humanistic Themes in the Art of the '
         'Renaissance',
         '圖像傳播學',
         '视觉传播',
         '秧歌',
         '赤地之戀',
         '亲密关系的变革',
         '十個詞彙裡的中國',
         '甜与权力\n\nSweetness and Power: The Place of Sugar in Modern History'],
 '囡囡': ['《建筑设计防火规范》图示',
        '风景园林植物配置',
        '中国古典园林史',
        '景观艺术学',
        '机器学习',
        '新刻绣像批评金瓶梅\n\n新刻绣像批评金瓶梅',
        '法国蓝带西餐烹饪宝典',
        '数据挖掘导论',
        '我爱·我家',
        '山海经'],
 '国际著名卡瓦利（Qawwali）音乐欣赏 - 播单 - 优酷视频': [],
 '坎特柏利': ['檸檬',
          '米澤穂信と古典部',
          '学校へ行けなかった私が「あの花」「ここさけ」を書くまで',
          'いまさら翼といわれても',
          'クラゲの食堂',
          '山之四季',
          '智惠子抄\n\n智恵子抄',
          '小说灯笼\n\nろまん燈籠',
          '小丑之花\n\n道化の華',
          '津轻\n\n津軽'],
 '基瑞尔': ['Fraternity Gang Rape',
         'Before We Were Yours: A Novel',
         'Almost Famous Women',
         'Margin Calls',
         "Don't Worry, He Won't Get Far on Foot",
         'Rabbit Hole',
         'Labor Day',
         'The Lost City of Z',
         'Wilson',
         'Capitalism with Chinese Characteristics'],
 '夏亦凉': ['妻妾成群',
         '湘行散记',
         '菜根谭',
         '生死场',
         '画堂香事',
         '万物静默如谜',
         '海邊的房間',
         '都是遗风在醉人',
         '你所不知道的夜晚'],
 '夕霏': ['郑天挺西南联大日记',
        '一个被出卖的杀手\n\nA Gun For Sale',
        '替身\n\n身代わり',
        '克苏鲁神话Ⅱ\n\nCthulhu Mythos',
        '西藏生死恋',
        '生于七十年代',
        '撕裂的梦境',
        '危险的邂逅\n\n另一种邂逅',
        '警察\n\nPoliti',
        '爱如繁星'],
 '夜半梦醒去外边': ['安迪·沃霍尔的哲学\n'
             '\n'
             'The philosophy of Andy Warhol : from A to B and back again',
             '东京日和\n\n東京日和',
             '美丽新世界\n\n美丽新世界',
             '存在主义咖啡馆\n'
             '\n'
             'At the Existentialist Café：Freedom,Being,and Apricot Cocktails',
             '周三漫画\n\nWednesday Comics',
             '现代艺术150年\n'
             '\n'
             'What Are You Looking At?: 150 Years of Modern Art in the '
             'Blink of an Eye',
             '惡魔人01',
             '龙珠1',
             '灌籃高手完全版 1\n\nSLAM DUNK',
             '20世紀少年01\n\n20世紀少年01-ともだち'],
 '夜没门': ['1984 动物农场',
         'After Effects影视合成与特效火星风暴',
         'ADOBE PREMIERE PRO CS5标准培训教材',
         '甜甜的忧伤\n\nKrasosmutnění',
         '一缕秀发\n\nPostřižiny',
         '中国兔子德国草',
         '他们说，我是幸运的\n\nLucky',
         '平凡的世界（全三册）'],
 '天黑以后猫不然': ['安娜·卡列尼娜',
             '旅行从客房开始（纪念版）',
             '我的职业是小说家\n\n職業としての小説家',
             '常常旅行',
             '西太后：薇薇安·威斯特伍德',
             '从煎蛋开始\n\nThe Kaufmann Mercantile Guide',
             '食帖16：大满足！就爱锅料理',
             '食帖19：下午茶时间到！',
             '哇！沙拉的教科书',
             '菜根谭'],
 '奥利': ['金色眼睛的映像',
        '心是孤独的猎手',
        '电影是什么？\n\nWhat is Cinema?',
        '樱桃的滋味：阿巴斯谈电影\n\nLessons with Kiarostami',
        '劝导',
        '伤心咖啡馆之歌',
        '琴声如诉\n\nModerato Cantabile',
        '论摄影\n\nOn Photography',
        '电影概论 (第2版)',
        '我生命中的电影\n\nLes films de ma vie'],
 '女神的秋裤': ['副本\n\nAltered Carbon',
           '銃夢01',
           '银河护卫队2\n'
           '\n'
           'Guardians of the Galaxy: The Complete Collection Volume 2',
           '蛤蟆的油',
           '攻殼機動隊(01)\n\n攻壳机动队',
           '攻殼機動隊(02)',
           '它\n\nIt',
           '西方电影史论'],
 '学霸になる': ['python机器学习\n\nPython Machine Learning',
           'Python数据科学导论',
           '新经济，新规则\n\nNew rules for the new economy',
           'Head First Python（中文版）',
           'HTTP权威指南\n\nHTTP: The Definitive Guide',
           '影响力\n\nInfluence: The Psychology of Persuasion',
           'Nanoweapons',
           '罗马人的故事（礼品装，全15册）',
           'Will Robots Take Your Job?',
           '我脑袋里的怪东西\n\nKafamda Bir Tuhaflik'],
 '安静': ['孩子们的诗',
        '记一忘三二',
        '现在就干',
        '大雪无痕',
        '不留心，看不见',
        '遥远的向日葵地',
        '给孩子们的诗',
        '日记中的爸爸舒芜',
        '金子美铃童谣集（全3册）',
        '给孩子的童年书'],
 '小弟有只猫': ['雕刻时光\n\nЗАПЕЧАТЛЕННОЕ ВРЕМЯ',
           '台湾电影史话',
           '当代电影艺术导论',
           '黄金时代\n\n黃金時代',
           '希区柯克的电影\n\nThe Films of Alfred Hitchcock',
           '独居的一年\n\nA Widow for One Year',
           '导演的诞生\n'
           '\n'
           'My First Movie, Take Two: Ten Celebrated Directors Talk About '
           'Their First Film',
           '明天也是小春日和\n\nあしたも、こはるびより。',
           '爱的饥渴\n\n愛の渇き',
           '快乐的死\n\nLa Mort Heureuse'],
 '小树': ['简·奥斯丁小说全集',
        'The Secret Library',
        '改变社会',
        '寂寞的游戏',
        '文明及其内涵\n\nCivilization and Its Contents',
        '追随科尔伯格',
        '道德发展心理学'],
 '尾生': ['卡拉马佐夫兄弟（上下册）（陀思妥耶夫斯基文集）\n\nБРАТЬЯ КАРАМАЗОВЫ',
        '一个叫欧维的男人决定去死\n\nEn Man Som Heter Ove',
        '红楼梦',
        '人类的群星闪耀时\n'
        '\n'
        'Sternstunden der Menschheit: Vierzehn historische Miniaturen',
        '施拉德论施拉德',
        '伟大的电影\n\nThe Great Movies',
        '刀锋',
        '树上的男爵\n\nThe Baron in the Trees'],
 '幸福妄想者': ['破晓',
           '诡案组',
           '格子间女人',
           "情人\n\nL'Amant",
           '鲤·孤独',
           '孤单乘客的神秘宴会(已绝版)',
           '一个人住第9年',
           '我想吃一个小孩',
           '吸血鬼全书',
           'A型人说明书 & B型人说明书\n\nB型人说明书'],
 '張小肆': ['米格尔街\n\nMiguel Street',
         '斯通纳\n\nStoner',
         '失明症漫记\n\nEnsaio sobre a Cegueira',
         '空荡荡的家\n\nThe Empty Family',
         '我生命中的电影\n\nLes films de ma vie',
         '南方高速\n\nCuentos completos 2',
         '献给爱米丽的一朵玫瑰花',
         '小妇人',
         '君主论\n\nIl Principe',
         '麦琪的礼物'],
 '放开那个浪味仙': ['富爸爸，穷爸爸\n\nRich Dad, Poor Dad',
             '超级英雄的秘密：金刚狼\n\nThe World According To Wolverine',
             '不义联盟：人间之神1\n\nInjustice: Gods Among Us Vol. 1',
             '冰与火之歌·卷一·权力的游戏（全三册）\n'
             '\n'
             'A Song of Ice and Fire1 A Game of Thrones',
             '知日·设计力',
             '漫步华尔街',
             "读心神探\n\nMind Hunter - Inside the FBI's Elite Serial Crime Unit",
             '故事\n\nStory',
             '你能去哪里，全在于你自己',
             '这里\n\nHere'],
 '放开那个西红柿': ['ANSI Common Lisp',
             '深入Linux内核架构\n\nProfessional Linux Kernel Architecture',
             '一生的性计划',
             '米开朗基罗',
             'UNIX/Linux 系统管理技术手册',
             '统计学习基础',
             '统计学习理论',
             'Principles',
             'Algorithms to Live By',
             'Expert C Programming'],
 '文文周': ['身体知道答案',
         '等雲到',
         '独唱团（第一辑）\n\n文艺复兴',
         '余光中詩選',
         '大逃港',
         '黑洞故事\n\n黑色脑力波',
         '七根凶简\n\n七根凶简',
         'The Fox Wish',
         '时间的女儿\n\nThe Daughter of Time',
         '人格转移杀人事件\n\n人格転移の殺人'],
 '春暧花开': ['百年孤独\n\nCien años de soledad',
          '自我训练',
          '101个心理治疗难题（万千心理）',
          '情感依附\n\nLives Across Time／Growing Up',
          '假性亲密关系',
          '积极情绪的力量'],
 '是草莓啊': ['多田便利屋\n\nまほろ駅前多田便利軒',
          '海边的卡夫卡',
          '数字城堡\n\nDigital Fortress',
          '懂得爱\n\nThe Relationship Garden',
          '意绵绵',
          '国王鞠躬，国王杀人\n\nDer König verneigt sich und tötet',
          '青春',
          '地尽头',
          '丝之屋\n\nThe House of Silk',
          '白色的乌鸦'],
 '林圆圆': ['奇迹之篷\n\nTenda dos Milagres',
         '怪诞故事集',
         '蒙田随笔全集·第一卷',
         '儿童杂事诗笺释',
         '朱天衣的作文课（全5册，随书赠含光盘）',
         '观海窥天\n\nLives of a Cell: Notes of a Biology Watcher',
         '猫'],
 '柏小齐': ['无言的宇宙\n'
         '\n'
         'The Universe in Zero Words:the Story of Mathematics As Told '
         'Through Equations',
         '天国之秋\n'
         '\n'
         'Autumn in the Heavenly Kingdom: China, the West, and the Epic '
         'Story of the Taiping Civil War',
         '李太白全集（全三冊）',
         '初识传播学（插图第7版）\n\nA First Look at Communication Theory,7e',
         '十二幅地图中的世界史\n\nA History of the World in Twelve Maps',
         '知觉之门\n\nThe Doors of Perception & Heaven and Hell',
         '怒\n\n怒り',
         '论人体科学与现代科技',
         '商君书',
         '历史的教训\n\nThe Lessons of History'],
 '樱桃小姐': ['骆驼祥子',
          '私房书',
          '山海经',
          '加缪手记\n\nCarnets I : Mai 1935 - février 1942',
          '你一生的故事\n\nStories of Your Life and Others',
          '木暮庄',
          '动物园\n\nZOO',
          '假如岁月足够长\n\n政と源',
          '同栖生活',
          '许三观卖血记'],
 '樹': ['明星制\n\nStardom: Industry of Desire',
       '演技六讲\n\nActing: The First Six Lessons',
       '里尔克《杜伊诺哀歌》述评',
       '美国独立电影制作',
       "空间的诗学\n\nLa poétique de la I'espace",
       '神话与意义',
       '希望为电影\n\nHope for Film',
       '手游与社交游戏设计：盈利模式与游戏机制解密',
       '媒介建构',
       '论普鲁斯特\n\nProust'],
 '欢乐分裂': ['真实眼泪之可怖\n'
          '\n'
          'The Fright of Real Tears: Krzystof Kieslowski between Theory and '
          'Post-Theory',
          '新千年幻想',
          '怪诞故事集',
          '风格练习\n\nExercices de style',
          '索尔·贝娄访谈录\n\nSaul Bellow: Settling My Accounts Before I Go Away',
          '房思琪的初恋乐园',
          '追寻逝去的时光：去斯万家那边\n'
          '\n'
          'A la Recherche du Temps Perdu Tome 1 Du Côté de chez Swann',
          '去斯万家那边',
          '虔诚的回忆\n\nSouvenirs pieux',
          '私语书（插图珍藏版）'],
 '江江江离岁': ['缘缘堂随笔',
           '山海经',
           '中国近代史',
           '小王子\n\nLe Petit Prince',
           '影响力\n\nInfluence: The Psychology of Persuasion',
           '越绝书',
           '人物志'],
 '汤圆圆': ['Dieu Et Nous Seuls Pouvons. Les Tres-Edifiants Et Tres-Inopines '
         'Memoires Des Pibrac de Bellerocaille',
         '春风沉醉的晚上',
         '瓦尔登湖',
         '雪国\n\nゆきぐに',
         '做愛時的眼神',
         '繁花',
         '我所有的朋友都死了\n\nAll My Friends Are Dead',
         '大仲马美食词典',
         '芬妮希爾\n\nFanny Hill'],
 '沈黎昕': ['阴阳师. 泷夜叉姬',
         '建筑力学与结构',
         '金子美铃童谣集（全3册）',
         '我的父亲郭沫若',
         '许子东讲稿-张爱玲.郁达夫.香港文学-卷二',
         '阅·独',
         '野兽派太太',
         '郑天挺西南联大日记',
         '第一次国共合作在广州',
         '落花水面皆文章'],
 '津五渡': ['刀与星辰',
         '我虚度的那部分世界',
         '国家的常识\n\nCountries and Concepts: Politics, Geography, Culture',
         '汉魏六朝诗选',
         '余光中诗选',
         '笑傲江湖（全四册）',
         '一个陌生女人的来信\n\nBrief einer Unbekannten',
         '一个人的KTV'],
 '流氓书生': ['祖先的爱情',
          '游隼\n\nThe Peregrine',
          '演技六讲\n\nActing: The First Six Lessons',
          '他们眼望上苍\n\nTheir Eyes Were Watching God',
          '斯通纳\n\nStoner',
          '世界散文精华（美洲卷）',
          '世界散文精华（欧洲卷）（上、下册）',
          '心的交会',
          '禅的智慧',
          '光与暗的故事\n\nIn Sunlight or In Shadow'],
 '温☪差': ['镖人\n\n鏢人',
         '编程之美\n\n程式之美',
         '城南旧事',
         '一句顶一万句',
         '代表作和被代表作',
         '中国现代小说史',
         '脚鱼\n\nDer Füsch',
         '单向历2018：铸黑版',
         '亲爱的日历·2018',
         '利维坦之书\n\nThe book of Leviathan'],
 '火枪手吱吱': ['电影史\n\nHISTOIRE(S) DU CINEMA',
           '娼年Call Boy',
           '焚舟纪\n\nBurning Your Boats',
           '二手时间\n\nВремя секонд хэнд',
           '纯白之夜',
           '春琴抄',
           '萨德侯爵夫人',
           "帷幕\n\nCurtain: Poirot's Last Case",
           '海鷗\n\nЧайка',
           '刀背藏身'],
 '犹在镜中': ['英雄变格',
          'Gramophone, Film, Typewriter',
          '大众传播理论',
          '导读德勒兹\n\nGilles Deleuze',
          '雾中风景',
          '房思琪的初恋乐园',
          '不敢问希区柯克的，就问拉康吧',
          '神话修辞术\n\nMythologies',
          '烹饪、菜肴与阶级\n'
          '\n'
          'Cooking, Cuisine and Class: A Study in Comparative Sociology'],
 '狐梨Icey': [],
 '狗男优': [],
 '甘': ['悟空传', '巨流河', '背包十年', '三体全集'],
 '登录豆瓣': [],
 '红  孩 儿': ['植物进化的艺术\n\nThe Art of Plant Evolution',
            '圖解日本陶瓷器入門',
            '雕刻时光\n\nSculpting in Time',
            '澄衷蒙学堂字课图说',
            '四川民居',
            '花图鉴',
            '物种起源\n\nThe Origin of Species',
            '哲学的慰藉\n\nThe Consolations of Philosophy',
            '白金数据\n\nプラチナデータ',
            '跃然脂上'],
 '胡萝卜有毒': ['身份的焦虑\n\nStatus Anxiety',
           '奥格威谈广告（全彩版）（精装）',
           '会计基础',
           '杰克·韦尔奇管理日志',
           '梦里花落知多少',
           '茅山后裔1',
           '国富论\n\nThe Wealth of Nations',
           '心理学与生活\n\nPsychology and life',
           '悉达多',
           '红顶商人胡雪岩\n\n胡雪岩 (上)'],
 '蒋大蛋': ['海龟交易法则',
         'JavaScript高级程序设计（第3版）\n\nProfessional JavaScript for Web',
         '最好的告别\n\nBeing Mortal: Medicine and What Matters in the End',
         'Ghetto at the Center of the World',
         '吾国与吾民',
         '图解HTTP',
         '深入浅出Node.js',
         '天才地理学\n'
         '\n'
         'The Geography of Genius: A Search for the World’s Most Creative '
         'Places from Ancient Athens to Silicon Valley',
         'The Arrival',
         '人月神话'],
 '蓦然、': ['裁決1', '完美世界4', '完美世界3', '完美世界2', '完美世界1'],
 '衡星🌟。': ['当时年少',
          '盛世狼烟',
          'Quantitative Investment Analysis (CFA Institute Investment '
          'Series)',
          '经济学',
          '人间食粮',
          '哥德尔、艾舍尔、巴赫\n\nGödel, Escher, Bach: An Eternal Golden Braid',
          '致D\n\nLettre à D.',
          '遗失的世界',
          '妈妈离婚记'],
 '让弗朗索瓦张': ['马上少年过\n\n馬上少年過ぐ',
            '神秘火焰\n\nFirestarter',
            '战火之外\n\nBeyond the Killing Fields',
            '跳舞女郎\n\nDancing girls',
            'Night Shift',
            '山羊兹拉特与其他故事',
            'Of Mice and Men\n\n人鼠之間',
            'Lord of the Flies',
            '希腊罗马神话',
            '与奥逊·威尔斯共进午餐\n\nMy Lunches with Orson'],
 '达斯·条': ['沙丘\n\nDUNE',
          '猎豹\n\nPanserhjert',
          '少数派报告\n\nThe Minority Report',
          '凯旋门',
          '柏林广场',
          '海浪',
          '真实眼泪之可怖\n'
          '\n'
          'The Fright of Real Tears: Krzystof Kieslowski between Theory and '
          'Post-Theory',
          '候场\n\nThe Half：Photographs of Actors Preparing for the Stage',
          "使女的故事\n\nThe Handmaid's Tale",
          'Blame! 1\n\n特警新人类'],
 '醉舞阡陌': ['信任代理',
          "我怎样毁了我的一生\n\nComment j'ai raté ma vie",
          'Getting Real',
          '乌合之众\n\nThe Crowd: A Study of the Popular Mind',
          '愿你出走半生，归来仍是少年',
          '南美洲',
          '黄帝内经',
          '藏地密码（全10册）',
          '动物农场\n\nAnimal Farm'],
 '长安笑笑生': ['世界电影史（第2版）',
           '伟大的电影\n\nThe Great Movies',
           '切·格瓦拉之死',
           '习近平谈治国理政',
           '我们这个时代的怕和爱',
           '长日留痕\n\nThe Remains of the Day',
           '无眠在世纪末',
           '脸的历史',
           '这就是达利\n\nThis is Dalí',
           '维以不永伤'],
 '阿塔': ['丰乳肥臀',
        '失落的秘符\n\nThe Lost Symbol',
        '希腊神话故事\n\n世界文学名著典藏·希腊神话故事',
        '英雄变格',
        '先锋派理论',
        '东方学',
        '茫茫黑夜漫游\n\nVoyage au bout de la nuit',
        '诗人导演费穆'],
 '阿让': ['我身在历史何处',
        '五个人的战争\n'
        '\n'
        'FIVE CAME BACK: A STORY OF HOLLYWOOD AND THE SECOND WORLD WAR',
        '粉丝文化读本',
        '电影理论解读\n\nFilm Theory : An Introduction',
        '拉片子',
        '双城故事',
        '中国电影理论史评',
        '与光同尘',
        '中国无声电影史',
        '美学散步'],
 '黄昏之鸟': ['布格缪勒钢琴进阶练习25首',
          '车尔尼钢琴初步教程作品599',
          '哈农钢琴练指法',
          '单向度的人',
          '音乐圣经',
          '最后的日记',
          '恋爱中的男人\n\nEin liebender mann',
          '真实眼泪之可怖\n'
          '\n'
          'The Fright of Real Tears: Krzystof Kieslowski between Theory and '
          'Post-Theory',
          '爱的进化论',
          '日益亲近'],
 }

persuaded_reader = {}